### ISSUE TITLE
RightClick crash

### ISSUE THREAD

**Issue by steve823** [crystalidea/anytoiso-public#33]
Using version 3.9.6 Pro with Windows ver 2004, build 19041.450 when I use the mouse Right Click causes the explorer window to close. Using the keyboard windows "menu" key also caused it to close.

**Comment by kleuter** [comment]
Did you try to disable the shell integration in the app Preferences?

**Comment by kleuter** [comment]
Caused by the NVIDIA shell extension, imroved in 4.0

**Comment by kleuter** [comment]
Fixed in the latest version
